### ISSUE TITLE
Url with subdomains redirect to localhost

### ISSUE THREAD

**Issue by frankdirosaiv** [fastly/ftw#100]
I am using the docker to run the suite of tests against a few projects I have live. This project works great against some of my hostnames, I am a big fan. However, when I test against some projects I have on PCF with a subdomain (example hello.myapp.io), I will get the following error:  

`HTTP/1.1 404 Not Found`
`Content-Type: text/plain; charset=utf-8`
`Date: Mon, 26 Nov 2018 17:19:01 GMT`
`X-Cf-Routererror: unknown_route`
`X-Content-Type-Options: nosniff`
`Content-Length: 61`
`Connection: keep-alive`

`404 Not Found: Requested route ('localhost') does not exist.`

This can be recreated by running the ftw suite of tests against pivotal.network.io.

Has anyone seen this issue before or know how to fix?

**Comment by csjperon** [comment]
Thanks for reporting this. Do you know which FTW test is being used when this happens?

**Comment by csjperon** [comment]
Actually if you use `-F` on the command line, whatever you are using as the destination address will be used to override the `Host:` header. Depending on your test, it sounds like the `Host:` header is set to localhost.

**Comment by csjperon** [comment]
I am going to close this for now, but please let us know if this didn't address your problem.

Thanks for the report!
