### ISSUE TITLE
CONTRIBUTORS.md

### ISSUE THREAD

**Issue by zmallen** [fastly/ftw#13]

**Comment by csanders-git** [comment]
you can

**Comment by jaredestroud** [comment]
Would you be interested in a a Travis CI check for PEP-8 compliance?

**Comment by zmallen** [comment]
that would be pretty bad imho, lots of FP if it fails.. dont think its worth it right now

**Comment by RyPeck** [comment]
You can add it as an `after_script` that won't affect the result of the build but will allow you to see the results of the run.
