### ISSUE TITLE
Vagrantfile w/ vanilla modsec

### ISSUE THREAD

**Issue by zmallen** [fastly/ftw#52]
We should have a Vagrantfile with a vanilla modsec deploy for quick testing

**Comment by zmallen** [comment]
We are working on publishing this Vagrantfile as a Chef cookbook in a separate repo. Will update this as it comes along, removing milestone v1.0 for now

**Comment by zmallen** [comment]
https://github.com/fastly/waf_testbed

**Comment by csjperon** [comment]
https://github.com/fastly/waf_testbed
Done
